/** Declaration file generated by dts-gen */

declare class knack {
    constructor(...args: any[]);

    create(...args: any[]): void;

    delete(...args: any[]): void;

    get(...args: any[]): void;

    getOne(...args: any[]): void;

    parse(...args: any[]): void;

    search(...args: any[]): void;

    update(...args: any[]): void;

    upload(...args: any[]): void;

    upsert(...args: any[]): void;

}


declare namespace knack {
    namespace prototype {
        function create(...args: any[]): void;

        function get(...args: any[]): void;

        function getOne(...args: any[]): void;

        function parse(...args: any[]): void;

        function search(...args: any[]): void;

        function update(...args: any[]): void;

        function upload(...args: any[]): void;

        function upsert(...args: any[]): void;

    }

}

